import { chromium } from "playwright";
import { mkdir } from "node:fs/promises";

const baseUrl = process.env.VERIFY_URL || "http://127.0.0.1:3000";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: "no-preference" });
const errors = [];
const failedRequests = [];
const consoleMessages = [];
page.on("pageerror", (error) => errors.push(error.message));
page.on("console", (message) => { consoleMessages.push(`${message.type()}: ${message.text()}`); if (message.type() === "error") errors.push(message.text()); });
page.on("requestfailed", (request) => failedRequests.push(`${request.url()} :: ${request.failure()?.errorText}`));
page.on("response", (response) => { if (response.status() >= 400) failedRequests.push(`${response.status()} ${response.url()}`); });
await page.goto(baseUrl, { waitUntil: "networkidle" });
const hydrated = await page.locator(".desktop[data-hydrated='true']").waitFor({ timeout: 5000 }).then(() => true).catch(() => false);
await page.getByRole("button", { name: "Start", exact: true }).click();
await page.waitForTimeout(100);
const startMenus = await page.locator(".start-menu").count();
await page.getByRole("button", { name: "Start", exact: true }).click();
const shortcut = page.getByRole("button", { name: "About me", exact: true }).first();
await shortcut.click();
await page.waitForTimeout(500);
const aboutWindows = await page.locator('[data-window="about"]').count();
await page.getByRole("button", { name: "Archive", exact: true }).first().click();
await page.waitForTimeout(250);
const archiveWindows = await page.locator('[data-window="archive"]').count();
await mkdir("artifacts", { recursive: true });
await page.screenshot({ path: "artifacts/home-desktop.png", fullPage: true });
const homeVisitorCounters = await page.locator(".visitor-counter:visible").count();
await page.goto(`${baseUrl}/guestbook`, { waitUntil: "networkidle" });
const guestbookNoindex = await page.locator('meta[name="robots"]').getAttribute("content");
const guestbookVisitorCounters = await page.locator(".visitor-counter:visible").count();
const guestbookDesktopOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
await page.screenshot({ path: "artifacts/guestbook-desktop.png", fullPage: true });
await page.goto(`${baseUrl}/archive`, { waitUntil: "networkidle" });
const archiveRegion = await page.getByRole("region", { name: "Archive Explorer" }).count();
const archiveDesktopOverflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
await page.getByRole("navigation", { name: "Filter archive by type" }).getByRole("link", { name: "Photos" }).click();
await page.waitForURL(/type=photos/);
const archiveFilterUrl = page.url();
await page.screenshot({ path: "artifacts/archive-desktop.png", fullPage: true });
const mobile = await browser.newPage({ viewport: { width: 412, height: 915 }, isMobile: true, hasTouch: true });
await mobile.goto(baseUrl, { waitUntil: "networkidle" });
await mobile.locator(".desktop[data-hydrated='true']").waitFor();
await mobile.screenshot({ path: "artifacts/home-mobile.png", fullPage: true });
const mobileNavigation = await mobile.getByRole("navigation", { name: "Site pages" }).count();
const mobileArchiveLinks = await mobile.getByRole("link", { name: /^Archive/ }).count();
await mobile.goto(`${baseUrl}/guestbook`, { waitUntil: "networkidle" });
const guestbookMobileOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
await mobile.screenshot({ path: "artifacts/guestbook-mobile.png", fullPage: true });
await mobile.goto(`${baseUrl}/archive`, { waitUntil: "networkidle" });
const archiveMobileOverflow = await mobile.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
await mobile.screenshot({ path: "artifacts/archive-mobile.png", fullPage: true });
const overlay = await page.locator("[data-nextjs-dialog]").count();
console.log(JSON.stringify({ title: await page.title(), content: (await page.locator("body").innerText()).length, hydrated, startMenus, aboutWindows, archiveWindows, mobileNavigation, mobileArchiveLinks, homeVisitorCounters, guestbookVisitorCounters, guestbookNoindex, guestbookDesktopOverflow, guestbookMobileOverflow, archiveRegion, archiveFilterUrl, archiveDesktopOverflow, archiveMobileOverflow, overlay, failedRequests, consoleMessages, errors }, null, 2));
await browser.close();
if (!hydrated || startMenus !== 1 || aboutWindows !== 1 || archiveWindows !== 1 || mobileNavigation !== 1 || mobileArchiveLinks < 1 || homeVisitorCounters !== 0 || guestbookVisitorCounters !== 1 || !guestbookNoindex?.includes("noindex") || guestbookDesktopOverflow || guestbookMobileOverflow || archiveRegion !== 1 || !archiveFilterUrl.includes("type=photos") || archiveDesktopOverflow || archiveMobileOverflow || overlay || failedRequests.length || errors.length) process.exitCode = 1;
